# Generated by Django 4.2.5 on 2025-05-31 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='observations/%Y/%m/')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obserwacje', to='plants.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obserwacje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obserwacja',
                'verbose_name_plural': 'Obserwacje',
                'ordering': ['-data'],
            },
        ),
    ]
