# Generated by Django 4.2.5 on 2025-05-31 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('gatunek', models.CharField(blank=True, max_length=255)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='plants/%Y/%m/')),
                ('data_dodania', models.DateField(auto_now_add=True)),
                ('ostatnie_podlanie', models.DateField(blank=True, null=True)),
                ('interwal_podlania', models.PositiveIntegerField(default=7, help_text='Interwał (w dniach) między podlaniami')),
                ('interwal_nawozenia', models.PositiveIntegerField(default=30, help_text='Interwał (w dniach) na nawożenie')),
                ('interwal_przesadzania', models.PositiveIntegerField(default=365, help_text='Interwał (w dniach) na przesadzanie')),
                ('oswietlenie', models.CharField(choices=[('low', 'Niskie'), ('medium', 'Średnie'), ('high', 'Wysokie')], default='medium', max_length=10)),
                ('ph_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('kategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roślina',
                'verbose_name_plural': 'Rośliny',
            },
        ),
    ]
